class AccountFrozenError(Exception):...

class AccountClosedError(Exception):...

class InvalidOperationError(Exception):...

class InsufficientFundsError(Exception):...

class AuthenticationError(Exception): ...

class ClientBlockedError(Exception): ...

class ClientNotFoundError(Exception): ...

class AccountNotFoundError(Exception): ...

class TransactionNotFoundError(Exception):...

class TransactionCancelledError(Exception):...

class TransactionValidationError(Exception):...

class RiskBlockedError(Exception):...